:DISCORD_APP_ID: 1234567
:DISCORD_TOKEN: supersecrettokengoeshere
example:
  :a_key: value
  :a_list:
  - thing1
  - thing2
  - thing3
weather:
  google_api: your_api_key_here
  forecastio_api: your_other_api_key_here
  emojis:
    clear-night: waxing_gibbous_moon
    clear-day: waxing_gibbous_moon
    partly-cloudy-night: partly_sunny
    partly-cloudy-day: partly_sunny
    rain: cloud_rain
    snow: cloud_snow
    sleet: cloud_rain
    wind: wind_blowing_face
    fog: foggy
    cloudy: cloud
    tornado: cloud_tornado
    thunderstorm: cloud_lightning